[package]
name = "web-form"
version = "1.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "krircc <krircc@qq.com>"]
edition = "2018"

[dependencies]
kayrx = {git = "https://github.com/kayrx/kayrx"}

serde = { version = "1.0", features = ["derive"] }
