[package]
name = "state"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "krircc <krircc@aliyun.com>"]
edition = "2018"

[dependencies]
kayrx = "0.7.0"
futures = "0.3.1"
env_logger = "0.6"
