[package]
name = "hello"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "krircc@qq.com"]
license = "MIT"
edition = "2018"

[dependencies]
kayrx = {git = "https://github.com/kayrx/kayrx"}
env_logger = "0.6"