[package]
name = "web-middleware"
version = "1.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "Sven-Hendrik Haase <svenstaro@gmail.com>", "krircc <krircc@aliyun.com>"]
edition = "2018"

[dependencies]
kayrx = "0.8.0"
futures = "0.3.1"
env_logger = "0.6"
bytes = "0.5"
pin-project = "0.4.6"