[package]
name = "basic"
version = "0.1.0"
authors = ["krircc <krircc@aliyun.com>"]
edition = "2018"

[dependencies]
kayrx = {git = "https://github.com/kayrx/kayrx"}
keclc-file = {git = "https://github.com/kayrx/keclc"}
futures = "0.3.1"	
env_logger = "0.5"	
bytes = "0.5" 