[package]
name = "web-cors"
version = "1.0.0"
authors = ["krircc <krircc@qq.com>"]
edition = "2018"

[dependencies]
kayrx = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.6"
futures = "0.3"
