[package]
name = "hello"
version = "0.1.0"
authors = ["krircc <krircc@qq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
meet = {path = "../../../meet"}


