[workspace]
members = [
  "async-ex",
  "async-sqlite",
  "async-web-client",
  "basic",
  "error_handle",
  "form",
  "hello",
  "http-proxy",
  "json",
  "multipart",
  "run-in-thread",
  "rustls",
  "state",
  "web-cors/backend",
  "web-middleware",
]
